-- Migration: Usage Tracking
-- Track monthly task usage and model costs per account

-- Monthly usage tracking
CREATE TABLE IF NOT EXISTS monthly_usage (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  month DATE NOT NULL, -- First day of month (e.g., '2026-02-01')
  tasks_used INTEGER DEFAULT 0,
  tasks_limit INTEGER NOT NULL, -- Pulled from plan tier
  tokens_in INTEGER DEFAULT 0,
  tokens_out INTEGER DEFAULT 0,
  cost_usd DECIMAL(10,6) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(account_id, month)
);

-- Add task-level tracking
ALTER TABLE mc_tasks 
  ADD COLUMN IF NOT EXISTS tokens_in INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tokens_out INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS model_used TEXT,
  ADD COLUMN IF NOT EXISTS cost_usd DECIMAL(10,6) DEFAULT 0;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_monthly_usage_account ON monthly_usage(account_id, month DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_model ON mc_tasks(model_used);
CREATE INDEX IF NOT EXISTS idx_tasks_created_month ON mc_tasks(account_id, DATE_TRUNC('month', created_at));

-- Comments
COMMENT ON TABLE monthly_usage IS 'Track monthly task usage per account for billing limits';
COMMENT ON COLUMN monthly_usage.tasks_limit IS 'Max tasks for current plan (100, 400, 1000, or NULL for unlimited)';
COMMENT ON COLUMN mc_tasks.tokens_in IS 'Input tokens consumed by this task';
COMMENT ON COLUMN mc_tasks.tokens_out IS 'Output tokens generated by this task';
COMMENT ON COLUMN mc_tasks.model_used IS 'Model used for execution (claude-3-5-sonnet, kimi-k2.5, etc)';
COMMENT ON COLUMN mc_tasks.cost_usd IS 'Estimated cost in USD for this task execution';

-- Function to get or create monthly usage record
CREATE OR REPLACE FUNCTION get_monthly_usage(account_uuid UUID, month_date DATE DEFAULT CURRENT_DATE)
RETURNS monthly_usage AS $$
DECLARE
  usage_record monthly_usage;
  account_limit INTEGER;
BEGIN
  -- Get account's plan limit
  SELECT 
    CASE plan_tier
      WHEN 'cloud' THEN 100      -- Solo
      WHEN 'cloud-developer' THEN 400
      WHEN 'cloud-plus' THEN 1000  -- Team
      ELSE NULL                    -- Free tiers = unlimited
    END INTO account_limit
  FROM accounts
  WHERE id = account_uuid;

  -- Get or create usage record for this month
  INSERT INTO monthly_usage (account_id, month, tasks_limit)
  VALUES (account_uuid, DATE_TRUNC('month', month_date), account_limit)
  ON CONFLICT (account_id, month) 
  DO UPDATE SET updated_at = NOW()
  RETURNING * INTO usage_record;

  RETURN usage_record;
END;
$$ LANGUAGE plpgsql;

-- Function to increment task count
CREATE OR REPLACE FUNCTION increment_task_usage(
  account_uuid UUID,
  tokens_input INTEGER DEFAULT 0,
  tokens_output INTEGER DEFAULT 0,
  cost DECIMAL DEFAULT 0
)
RETURNS VOID AS $$
BEGIN
  INSERT INTO monthly_usage (account_id, month, tasks_used, tokens_in, tokens_out, cost_usd, tasks_limit)
  VALUES (
    account_uuid,
    DATE_TRUNC('month', CURRENT_DATE),
    1,
    tokens_input,
    tokens_output,
    cost,
    (SELECT CASE plan_tier
      WHEN 'cloud' THEN 100
      WHEN 'cloud-developer' THEN 400
      WHEN 'cloud-plus' THEN 1000
      ELSE NULL
    END FROM accounts WHERE id = account_uuid)
  )
  ON CONFLICT (account_id, month)
  DO UPDATE SET
    tasks_used = monthly_usage.tasks_used + 1,
    tokens_in = monthly_usage.tokens_in + tokens_input,
    tokens_out = monthly_usage.tokens_out + tokens_output,
    cost_usd = monthly_usage.cost_usd + cost,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Function to check if account is over limit
CREATE OR REPLACE FUNCTION is_over_limit(account_uuid UUID)
RETURNS BOOLEAN AS $$
DECLARE
  usage_record monthly_usage;
BEGIN
  usage_record := get_monthly_usage(account_uuid);
  
  -- NULL limit = unlimited (free tiers)
  IF usage_record.tasks_limit IS NULL THEN
    RETURN FALSE;
  END IF;
  
  RETURN usage_record.tasks_used >= usage_record.tasks_limit;
END;
$$ LANGUAGE plpgsql;

-- Update plan_tier to include new developer tier
COMMENT ON COLUMN accounts.plan_tier IS 'Subscription tier: free, cloud (Solo $19), cloud-developer ($49), cloud-plus (Team $99)';
