-- ============================================
-- 019: Briefings & Email Intelligence
-- Daily briefings, extracted items, user prefs
-- ============================================

-- Daily briefings generated by the briefing engine
CREATE TABLE IF NOT EXISTS briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  content JSONB NOT NULL DEFAULT '{}',
  sections JSONB NOT NULL DEFAULT '{}',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- One briefing per user per day
  UNIQUE(account_id, date)
);

CREATE INDEX IF NOT EXISTS idx_briefings_account_date
ON briefings(account_id, date DESC);

-- Row Level Security
ALTER TABLE briefings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users view own briefings" ON briefings;
CREATE POLICY "Users view own briefings" ON briefings
  FOR SELECT USING (account_id IN (SELECT id FROM accounts WHERE auth_uid = auth.uid()));

DROP POLICY IF EXISTS "Service role briefings" ON briefings;
CREATE POLICY "Service role briefings" ON briefings
  FOR ALL USING (auth.role() = 'service_role');


-- Items extracted from email, calendar, and other sources
CREATE TABLE IF NOT EXISTS extracted_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  source TEXT NOT NULL,           -- 'email', 'calendar', 'browser'
  source_id TEXT,                 -- message ID, event ID, etc.
  type TEXT NOT NULL,             -- 'flight', 'hotel', 'bill', 'invite', 'action_item', 'subscription', 'delivery'
  title TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}',  -- structured extraction (dates, amounts, confirmation #s, etc.)
  processed BOOLEAN DEFAULT FALSE,   -- has this been acted on (event created, task made, etc.)
  dismissed BOOLEAN DEFAULT FALSE,   -- user dismissed this extraction
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ             -- optional: when this item is no longer relevant
);

CREATE INDEX IF NOT EXISTS idx_extracted_items_account
ON extracted_items(account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_extracted_items_type
ON extracted_items(account_id, type)
WHERE NOT dismissed AND NOT processed;

CREATE INDEX IF NOT EXISTS idx_extracted_items_source
ON extracted_items(account_id, source, source_id);

-- Row Level Security
ALTER TABLE extracted_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users view own extracted items" ON extracted_items;
CREATE POLICY "Users view own extracted items" ON extracted_items
  FOR SELECT USING (account_id IN (SELECT id FROM accounts WHERE auth_uid = auth.uid()));

DROP POLICY IF EXISTS "Service role extracted items" ON extracted_items;
CREATE POLICY "Service role extracted items" ON extracted_items
  FOR ALL USING (auth.role() = 'service_role');


-- Extend user preferences for briefing settings
-- (mc_user_preferences already exists from migration 016)
ALTER TABLE mc_user_preferences
ADD COLUMN IF NOT EXISTS briefing_time TEXT DEFAULT '06:00',
ADD COLUMN IF NOT EXISTS briefing_email BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS briefing_sections JSONB DEFAULT '{"schedule": true, "tasks": true, "email_intel": true, "agent_activity": true, "suggestions": true}',
ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'America/New_York',
ADD COLUMN IF NOT EXISTS reminder_config JSONB DEFAULT '{"escalation_days": [1, 3, 7], "email_escalation": true}';

COMMENT ON TABLE briefings IS 'Daily AI-generated briefings. One per user per day. Content is a structured JSON with sections for schedule, tasks, email intelligence, agent activity, and suggestions.';
COMMENT ON TABLE extracted_items IS 'Items extracted from email and other sources. Flights, bills, invites, action items. Processed flag indicates if Tiker has acted on it (created event, task, etc.).';
